modLoader = "javafml" #mandatory
loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "MIT" # Review your options at https://choosealicense.com/.
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId = "medievalorigins" #mandatory
version = "${version}" #mandatory
displayName = "MedievalOriginsRevival" #mandatory
refmapName="medievalorigins.refmap.json"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile = "icon.png" #optional (needs to be in the root of your mod jar (root of your 'resources' folder))
credits = "Thank you for this template MerchantPug you saved my life" #optional
authors = "Muon" #optional
description = 'Origins inspired by mythology, fantasy, and the medieval era' #mandatory (Supports multiline text)
[[dependencies.medievalorigins]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[47.1,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.medievalorigins]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
[[dependencies.medievalorigins]]
modId = "pehkui"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"


